spring:
  application:
    name: config-server
  cloud:
    config:
      label: zhangds
      server:
        git:
          uri: https://github.com/zhangds-by/springcloud
          searchPaths: respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/